name: Build Linux Kernel

on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        linux: [debian, kalilinux, linux-mint, ubuntu,
          almalinux, amazonlinux,
          centos, centos8, fedora, mageia,
          opensuse, oraclelinux, rockylinux,
          archlinux, manjarolinux,
          cbl-mariner, chimeralinux,
          gentoo, solus, void-linux]
          # parrot
          # redhat
    uses: ./.github/workflows/build.yml
    with:
      linux: ${{ matrix.linux }}

