name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t build-kernel .
      - name: Build Linux Kernel
        run: docker run -it build-kernel
