on:
  workflow_call:
    inputs:
      linux:
        description: 'Name of Linux distribution to build Linux Kernel'
        default: ubuntu
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker compose build ${{ inputs.linux }}
      - name: Build Linux Kernel
        run: docker compose run --rm --env CI=$CI --service-ports ${{ inputs.linux }}

