name: Build Linux Kernel

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        linux: [debian, kalilinux, linux-mint, ubuntu,
          almalinux, amazonlinux,
          centos, centos8, fedora, # mageia
          opensuse, rockylinux, # oraclelinux
          archlinux, cbl-mariner, chimeralinux,
          gentoo, parrot, solus, void-linux]
          # manjarolinux
          # redhat
    uses: ./.github/workflows/build.yml
    with:
      linux: ${{ matrix.linux }}

